### ISSUE TITLE
calls from frontend to backend are not truely async

### ISSUE THREAD

**Issue by mohithpothineni** [namuyan/async-Eel#2]
for every request from front end the _process_message is called by spawn in eel framework but here you are simply doing await _process_message() so it is not scheduled on event loop so not being truely async

Solution:
in __init__.py file change the line 211 from 

await _process_message(message, ws) to

asyncio.create_task(_process_message(message, ws))

**Comment by mohithpothineni** [comment]
please refer this
https://stackoverflow.com/questions/33357233/when-to-use-and-when-not-to-use-python-3-5-await/33399896#33399896

**Comment by namuyan** [comment]
fixed by: https://github.com/namuyan/async-Eel/pull/3
